import turtle
t = turtle.Pen()
t.speed(50)

def uklad():
    t.backward(275)
    t.forward(550)
    t.begin_fill()
    t.left(90)
    t.forward(5)
    t.backward(10)
    t.right(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.end_fill()
    t.left(120)
    t.forward(5)
    t.right(90)
    t.forward(275)
    t.left(90)
    t.forward(275)
    t.left(180)
    t.forward(550)
    t.begin_fill()
    t.left(90)
    t.forward(5)
    t.backward(10)
    t.right(60)
    t.forward(10)
    t.left(120)
    t.forward(10)
    t.end_fill()
    t.left(120)
    t.forward(5)
    t.right(90)
    t.forward(275)
    t.left(90)
    t.backward(275)
    for num in range(21):
        t.forward(25)
        t.left(90)
        t.forward(5)
        t.forward(-10)
        t.forward(5)
        t.right(90)
            
    t.backward(250)
    t.right(90)
    t.forward(275)
    t.left(180)
    for num in range(21):
        t.forward(25)
        t.left(90)
        t.forward(5)
        t.forward(-10)
        t.forward(5)
        t.right(90)
    t.backward(250)
    t.up()
    t.forward(-25)
    for num in range(1, 12, +1):
        if num == 11:
            t.up()
            t.right(90)
            t.forward(25)
            t.left(90)
            t.down()
            t.write("X", move=False, align='center', font=('Arial', 8, 'normal'))
        else:
            t.up()
            t.right(90)
            t.forward(25)
            t.left(90)
            t.down()
            t.write(num, move=False, align='center', font=('Arial', 8, 'normal'))
    t.up()
    t.left(90)
    t.forward(550)
    t.right(90)
    for num in range(-10, 0, +1):
        t.up()
        t.right(90)
        t.forward(25)
        t.left(90)
        t.down()
        t.write(num, move=False, align='center', font=('Arial', 8, 'normal'))
    t.up()
    t.forward(25)
    t.right(90)
    t.forward(25)
    t.right(90)
    t.forward(275)
    t.left(180)
    t.forward(25)
    t.left(90)
    t.forward(10)
    t.write("-10", move=False, align='center', font=('Arial', 8, 'normal'))
    t.forward(-10)
    t.down()
    for num in range(-9, 12, +1):
        if num == 11:
            t.right(90)
            t.forward(25)
            t.left(90)
            t.forward(10)
            t.down()
            t.write("Y", move=False, align='center', font=('Arial', 8, 'normal'))
            t.up()
            t.forward(-10)
        else:
            t.right(90)
            t.forward(25)
            t.left(90)
            t.forward(10)
            t.down()
            t.write(num, move=False, align='center', font=('Arial', 8, 'normal'))
            t.up()
            t.forward(-10)

x = [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = []
def yTab():
    for i in range (len(x)):
            y.append(0)
            y[i] = a*x[i] + b

def wypelnij():
    t.setx(x[0] * 25)
    t.sety(y[0] * 25)
    for i in range(len(x)):
        t.dot()
        t.down()
        t.goto(x[i] * 25, y[i] *25)
    

uklad()
print('Podaj a i b dla funkcji y = a * x + b')
a = int(input('Podaj a: '))
b = int(input('Podaj b: '))
yTab()
wypelnij()

