from turtle import *
speed(50)

def uklad():
    bk(275)
    fd(550)
    begin_fill()
    lt(90)
    fd(5)
    bk(10)
    rt(60)
    fd(10)
    lt(120)
    fd(10)
    end_fill()
    lt(120)
    fd(5)
    rt(90)
    fd(275)
    lt(90)
    fd(275)
    lt(180)
    fd(550)
    begin_fill()
    lt(90)
    fd(5)
    bk(10)
    rt(60)
    fd(10)
    lt(120)
    fd(10)
    end_fill()
    lt(120)
    fd(5)
    rt(90)
    fd(275)
    lt(90)
    bk(275)
    for num in range(21):
        fd(25)
        lt(90)
        fd(5)
        fd(-10)
        fd(5)
        rt(90)
            
    bk(250)
    rt(90)
    fd(275)
    lt(180)
    for num in range(21):
        fd(25)
        lt(90)
        fd(5)
        fd(-10)
        fd(5)
        rt(90)
    bk(250)
    up()
    fd(-25)
    for num in range(1, 12, +1):
        if num == 11:
            up()
            rt(90)
            fd(25)
            lt(90)
            down()
            write("X", move=False, align='center', font=('Arial', 8, 'normal'))
        else:
            up()
            rt(90)
            fd(25)
            lt(90)
            down()
            write(num, move=False, align='center', font=('Arial', 8, 'normal'))
    up()
    lt(90)
    fd(550)
    rt(90)
    for num in range(-10, 0, +1):
        up()
        rt(90)
        fd(25)
        lt(90)
        down()
        write(num, move=False, align='center', font=('Arial', 8, 'normal'))
    up()
    fd(25)
    rt(90)
    fd(25)
    rt(90)
    fd(275)
    lt(180)
    fd(25)
    lt(90)
    fd(10)
    write("-10", move=False, align='center', font=('Arial', 8, 'normal'))
    fd(-10)
    down()
    for num in range(-9, 12, +1):
        if num == 11:
            rt(90)
            fd(25)
            lt(90)
            fd(10)
            down()
            write("Y", move=False, align='center', font=('Arial', 8, 'normal'))
            up()
            fd(-10)
        else:
            rt(90)
            fd(25)
            lt(90)
            fd(10)
            down()
            write(num, move=False, align='center', font=('Arial', 8, 'normal'))
            up()
            fd(-10)

x = [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = []
def yTab():
    for i in range (len(x)):
            y.append(0)
            y[i] = a*x[i] + b

def wypelnij():
    setx(x[0] * 25)
    sety(y[0] * 25)
    for i in range(len(x)):
        dot()
        down()
        goto(x[i] * 25, y[i] *25)
    

uklad()
print('Podaj a i b dla funkcji y = a * x + b')
a = int(input('Podaj a: '))
b = int(input('Podaj b: '))
yTab()
wypelnij()

